/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-23 16:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.intro;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class intro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/intro/../menu.jsp", Long.valueOf(1650729896697L));
    _jspx_dependants.put("/intro/../link.txt", Long.valueOf(1650707205635L));
    _jspx_dependants.put("/intro/../footer.jsp", Long.valueOf(1650729964323L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>학과소개 | Al소프트웨어학과</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/bootstrap-5.1.3-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/header.content0b7a.css?after\" />");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">					\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand navbar-light bg-light\">\r\n");
      out.write("	<div class=\"container\" style=\"display:block\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto\">\r\n");
      out.write("				<div class=\"navbar-header\">\r\n");
      out.write("					<div class=\"bottom-header-box\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<a class=\"text-decoration-none\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" title=\"홈 바로가기\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-logo.png\" alt=\"KNU\">\r\n");
      out.write("									<br><span class=\"logo-txt\">AI소프트웨어학과</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"logo-bottom\">KANGWON NATIONAL UNIVERSITY</p>\r\n");
      out.write("							</a>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto ps-0 pe-0\">\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarNavLightDropdown\">\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학과소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/greetings.jsp\">인사말</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history04.jsp\">학과연혁</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/intro.jsp\">학과소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/lab.jsp\">실습실소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/circle.jsp\">동아리소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/council.jsp\">학생회소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/location.jsp\">오시는 길</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								교수소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">교수</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">명예교수</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학사안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" target=\"_blank\" href=\"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37&key=1176&)\">학사공지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">교육과정</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">편성교과목</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/info.jsp\">학사정보</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">학사일정</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								입학안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admission/admission-guide.jsp\">모집요강</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								커뮤니티\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">공지사항</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">갤러리</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">서식자료실</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto pe-0\">\r\n");
      out.write("				<div class=\"row g-2 align-items-center\">\r\n");
      out.write("					<form class=\"col-auto\">\r\n");
      out.write("						<div class=\"row g-2 justify-content-end\" style=\"max-width: 260px\">\r\n");
      out.write("							<div class=\"col-8\">\r\n");
      out.write("								<input type=\"password\" class=\"form-control\" id=\"inputPassword2\" placeholder=\"Search\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-success\">Search</button>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"col-auto\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("    <p class=\"h2 fw-bold\">학과소개</p>\r\n");
      out.write("    <br>		\r\n");
      out.write("    <div class=\"content-box\">\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">AI소프트웨어학과 소개</h4>\r\n");
      out.write("        <p class=\"con-p no-pd\">오늘날 인공지능은 전 세계 수많은 산업시스템에서 작동하고 있으며, AI소프트웨어학과는 이를 리드하기위한 인재교육을 목표로 한다. 컴퓨터과학, 데이터과학, 산업공학, 미디어공학, 응용수학 등 다양한 기술의 융합교육으로, 4차산업혁명 시대의 핵심기술인 인공지능 및 소프트웨어기술을 선도하는 인재를 양성한다. 인공지능 기반의 스마트 어플리케이션, IoT시스템, 스마트미디어, 가상현실 및 혼합현실 등의 4차산업혁명 시대의 핵심산업을 기획 및 구축할 수 있는 능력을 갖춘 전문가를 양성하는 것을 목표로 하고 있다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">교육과정</h4>\r\n");
      out.write("        <div class=\"table-wrap\">\r\n");
      out.write("          <table class=\"table table-bordered\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("              <col width=\"15%\">\r\n");
      out.write("              <col width=\"*\">\r\n");
      out.write("            </colgroup>\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th class=\"text-center\" scope=\"col\">학년</th>\r\n");
      out.write("                <th class=\"text-center\" scope=\"col\">교과목명</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">1</td>\r\n");
      out.write("                <td>AI소프트웨어개론및응용, AI응용수학, 컴퓨팅사고력, &nbsp;코딩의 이해와 활용</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">2</td>\r\n");
      out.write("                <td >데이터사이언스프로그래밍, 머신러닝을위한통계학, 생산관리, CAD, 확률및통계, 미디어개론, 객체지향프로그래밍, 머신러닝을위한선형대수, AI와사운드, 고급프로그래밍, 소프트웨어공학, 미디어콘텐츠설계, 데이터구조, 디지털논리설계, 문제해결프로그래밍</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">3</td>\r\n");
      out.write("                <td>최적화및기계학습, 품질경영, 비즈니스커뮤니케이션, 데이터베이스, 빅데이터분석, 컴퓨터구조, 웹프로그래밍, 딥러닝을위한수치해석, ERP, 스토리지시스템, 미디어통신공학, 모바일프로그래밍, 사물인터넷, 운영체제</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">4</td>\r\n");
      out.write("                <td>신뢰성관리, 실험계획법, 설비보전관리, 재고관리, 벤처캡스톤디자인, 패턴인식, 스마트산업과창업가정신, 방송통신시스템, 제품설계및개발, 데이터마이닝, 컴퓨터보안, 컴퓨터네트워크, 메타버스</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">학과자랑거리(학과 장학금, 특색 있는 프로그램 등)</h4>\r\n");
      out.write("        <ul class=\"ul-type01\">\r\n");
      out.write("          <li>매년 성적 및 생활형편에 따라 전공에서 마련한 재원으로 장학금 지급</li>\r\n");
      out.write("          <li>대외활동 우수자 및 학과 발전에 기여한 학생(5~6명)을 선발하여 매년 기업에서 기부된 발전기금 장학금 수여</li>\r\n");
      out.write("          <li>자격증 취득, 프로그램 코드분석 및 개선, 팀프로젝트 수행을 통한 프로그래밍 능력 및 팀워크 향상 등 취업에 필요한 역량강화를 위해 프로그램 운영</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">학과(전공) 관련 추천 웹사이트</h4>\r\n");
      out.write("        <ul class=\"ul-type01\">\r\n");
      out.write("          <li>AI Hub - 인공지능 통합 플랫폼</li>\r\n");
      out.write("          <li>한국지능정보사회진흥원</li>\r\n");
      out.write("          <li>한국인공지능학회</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">졸업 후 진로</h4>\r\n");
      out.write("        <ul class=\"ul-type01\">\r\n");
      out.write("          <li>진학 : 학&middot;석사 연계과정, 대학원 석사 및 박사과정</li>\r\n");
      out.write("          <li>진로 : 공기업, 공무원, 프로그래머, 인공지능엔지니어, Data Scientist(빅데이터 분석 및 데이터마이닝), 스마트미디어개발자, 게임개발자, 가상현실개발자</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">졸업생 주요 진출분야</h4>\r\n");
      out.write("        <div class=\"table-wrap\">\r\n");
      out.write("          <table class=\"table table-bordered\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("              <col width=\"*\">\r\n");
      out.write("              <col width=\"*\">\r\n");
      out.write("            </colgroup>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">서석빈 (14학번) EFTech</td>\r\n");
      out.write("                <td class=\"text-center\">유인혁 (11학번) 바이브 컴퍼니</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">김진영 (16학번) 펜타시큐리티</td>\r\n");
      out.write("                <td class=\"text-center\">장건희 (14학번) 바이브 컴퍼니</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">김완일 (12학번) 효성티앤에스</td>\r\n");
      out.write("                <td class=\"text-center\">정은선 (14학번) VMS 솔루션</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"text-center\">김동현 (12학번) ㈜문엔지니어링</td>\r\n");
      out.write("                <td class=\"text-center\">김남호 (10학번) CJ E&amp;M</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">이런 학생이 오면 좋아요.</h4>\r\n");
      out.write("        <ul class=\"ul-type01\">\r\n");
      out.write("          <li>인공지능 및 소프트웨어 역량 강화를 통해 우수한 인재로 성장하기 위한 지능정보와 프로그래밍에 관심이 많은 학생</li>\r\n");
      out.write("          <li>대외활동을 직접 주최하거나 참가하여 실무역량을 길러 취창업 중심의 창의적인 인재가 되고자 하는 학생</li>\r\n");
      out.write("          <li>프로젝트와 봉사활동을 기획하여 기업에서 필요로 하는 인재로 성장하고자 하는 학생</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">재학생 인터뷰</h4>\r\n");
      out.write("        <p class=\"con-p no-pd\">Q1. 가장 관심 있는 분야와 그 이유를 말씀해주세요.<br>A1. 가상현실, 데이터과학, 인공지능 4차 산업관련 분야에 관심이 많으며 이는 미래의 다양한 IT 기술에 접목하여 발전할 것이라 예상되기 때문입니다.<br>Q2. 자신의 꿈이나 장래 희망은 무엇인가요?<br>A2. 인공지능전문가가 되어 미래에 대한 예측을 제 손으로 이루어 보고 싶습니다.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"con-box no-pd\">\r\n");
      out.write("        <h4 class=\"h4-tit01\">학과/전공 관련 추천도서</h4>\r\n");
      out.write("        <div class=\"text-center pb-5\"><img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/aisw/img/intro/img-intro.gif\" alt=\"2030 축의 전환(마우로 F.기옌), 부의 본능(브라운 스톤), 1년 안에 AI빅데이터 전문가가 되는 법\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("	<div class=\"row justify-content-between rounded p-3\" style=\"background: #D6D8D9\">\r\n");
      out.write("		<div class=\"col-auto ps-0\">\r\n");
      out.write("			<div>\r\n");
      out.write("				");

					String[] myHref = {"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=9&key=79", "https://www.kangwon.ac.kr/www/contents.do?key=334", "https://www.kangwon.ac.kr/www/contents.do?key=343", 
									   "#", "https://www.kangwon.ac.kr/www/selectEmpList.do?key=55", "https://www.academyinfo.go.kr/popup/pubinfo1690/list.do?schlId=0000003"};
					String[] myText = {"청렴행정", "개인정보처리방침","이메일주소수집거부",
									   "웹마스터", "전화번호검색", "대학정보공시"};

					if(myHref.length == myText.length)
					{
						for(int i = 0; i < myHref.length; i++)
						{
				
      out.write("\r\n");
      out.write("							<a class=\"text-decoration-none visit-orange\" target=\"_blank\" href=");
      out.print(myHref[i]);
      out.write('>');
      out.print(myText[i]);
      out.write("</a>\r\n");
      out.write("				");

							if(i < myHref.length - 1) out.println("|");
						}
					}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"btn btn-secondary dropdown-toggle px-3 py-2 fw-normal fs-4\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-offset=\"0,-800\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("					교내사이트 바로가기\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("					<div>\r\n");
      out.write("						");

							String[] otherHref = {"http://knugift.co.kr/", "https://cube.kangwon.ac.kr/portal/index", "https://cms.kangwon.ac.kr/padm/life/general-notice.do?mode=view&articleNo=243895&article.offset=760&articleLimit=10", 
											      "http://knufc.kr/bbs/login.php", "https://tpsc.kangwon.ac.kr/", "https://curriculum.kangwon.ac.kr/", "https://linc.kangwon.ac.kr/", "https://fund.kangwon.ac.kr/", 
											      "https://www.knuh.or.kr/main/main.asp", "http://knup.kangwon.ac.kr/", "https://ile.kangwon.ac.kr:44303/", "https://kculture.kangwon.ac.kr/", "http://knubiornd.com/", "https://kiit.kr/lang_kr.php?pid=index",
											      "https://kwbi.kangwon.ac.kr/", "http://old.kwclab.co.kr/", "http://clab.kwclab.co.kr/default.asp", "http://gongja.kangwon.ac.kr/", "https://icee.kangwon.ac.kr/", "https://gifted.kangwon.ac.kr/",
											      "https://faculty.kangwon.ac.kr/", "https://kile.kangwon.ac.kr/", "http://keri.kangwon.ac.kr/", "https://teacher.kangwon.ac.kr/teacher/index.do", "https://itl.kangwon.ac.kr/",
											      "https://oiaknu.kangwon.ac.kr/oiaknu/index.do", "http://www.iird.or.kr/", "https://www.kangwon.ac.kr/kwrc/index.do", "https://www.kbsi.re.kr/", "http://alsri.kangwon.ac.kr/", "http://www.nongsa.or.kr/"};
							String[] otherText = {"KNU 기념품 쇼핑몰", "KNU-큐브 & 메이커스페이스", "강원권역 e-러닝 지원센터", "강원대학교 교수회", "강원대학교 교원양성지원센터",
											      "강원대학교 교육과정", "강원대학교LINC사업단", "강원대학교 발전기금재단", "강원대학교병원", "강원대학교신문방송사",
											      "강원대학교평생학습중심대학", "강원문화연구소", "강원웰빙특산물산업화지역혁신센터", "강원종합기술연구원", "강원창업보육센터",
											      "공동실헙실습관", "공동실헙실습관(삼척)", "공자학원", "공학교육혁신센터", "과학영재교육원",
											      "교원초빙", "교양교육원", "교육연구소", "교육연수원", "교육혁신원",
											      "국제교류처", "국제농촌개발협력사업단", "글쓰기센터", "기초과학연구소", "농업생명과학연구원", "농촌사회교육원"};

							if(otherHref.length == otherText.length)
							{
								for(int i = 0; i < otherHref.length; i++)
								{
						
      out.write("\r\n");
      out.write("									<li class=\"dropdown-item\"><span class=\"px-2\">•</span><a class=\"text-decoration-none\" target=\"_blank\" href=");
      out.print(otherHref[i]);
      out.write('>');
      out.print(otherText[i]);
      out.write("</a></li>\r\n");
      out.write("						");

								}
							}
						
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row mt-3 mb-5\">\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<img style=\"width:200px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-footer-logo.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto p-0 ms-5\">\r\n");
      out.write("			<div class=\"row row-cols-1\" style=\"font-size:13px;max-width:800px\">\r\n");
      out.write("				<div class=\"col-auto pb-3\">\r\n");
      out.write("					강원도 삼척시 중앙로 346 강원대학교 삼척캠퍼스 5공학관 5층 | 대표전화: \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6370\" title=\"전화걸기\">033-570-6370</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6340\" title=\"전화걸기\">6430</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6580\" title=\"전화걸기\">6580</a> | 팩스 : 033-570-6379, 6589\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto\">\r\n");
      out.write("					COPYRIGHT (C) 2017 BY KANGWON NATIONAL UNIVERSITY.ALL RIGHTS RESERVED.\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/jquery/jquery-3.6.0.slim.min.js\"></script>\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("			");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
