/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-06-05 17:33:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bachelor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;

public final class curriculum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/bachelor/../community/freeboard/dbconn.jsp", Long.valueOf(1652100541898L));
    _jspx_dependants.put("/bachelor/../link.txt", Long.valueOf(1650707205635L));
    _jspx_dependants.put("/bachelor/../footer.jsp", Long.valueOf(1650729964323L));
    _jspx_dependants.put("/bachelor/../menu.jsp", Long.valueOf(1654446897525L));
    _jspx_dependants.put("/bachelor/../community/freeboard/freeboard.jsp", Long.valueOf(1654446655872L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/top-of-curriculum.content350a.css\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/bootstrap-5.1.3-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/header.content0b7a.css?after\" />");
      out.write("\r\n");
      out.write("<title>학생회소개 | AI소프트웨어학과</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<nav class=\"row navbar navbar-expand navbar-light bg-light\">\r\n");
      out.write("		<div class=\"row justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto\">\r\n");
      out.write("				<div class=\"navbar-header\">\r\n");
      out.write("					<div class=\"bottom-header-box\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<a class=\"text-decoration-none\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" title=\"홈 바로가기\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-logo.png\" alt=\"KNU\">\r\n");
      out.write("									<br><span class=\"logo-txt\">AI소프트웨어학과</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"logo-bottom\">KANGWON NATIONAL UNIVERSITY</p>\r\n");
      out.write("							</a>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto ps-0 pe-0\">\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarNavLightDropdown\">\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학과소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/greetings.jsp\">인사말</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history04.jsp\">학과연혁</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/intro.jsp\">학과소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/lab.jsp\">실습실소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/circle.jsp\">동아리소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/council.jsp\">학생회소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/location.jsp\">오시는 길</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								교수소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">교수</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"#\">명예교수</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학사안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" target=\"_blank\" href=\"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37&key=1176&)\">학사공지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/curriculum.jsp\">교육과정</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/subject.jsp\">편성교과목</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/info.jsp\">학사정보</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/calendar.jsp\">학사일정</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								입학안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admission/admission-guide.jsp\">모집요강</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								커뮤니티\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=freeboard\">공지사항</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=gallery\">갤러리</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=dataroom\">서식자료실</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto pe-0\">\r\n");
      out.write("				<div class=\"row g-2 align-items-center\">\r\n");
      out.write("					<form class=\"col-auto m-0\">\r\n");
      out.write("						<div class=\"row g-2 justify-content-end\" style=\"max-width: 260px\">\r\n");
      out.write("							<div class=\"col-8\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"search\" placeholder=\"Search\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-success\">Search</button>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"col-auto m-0\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<h3 class=\"fw-bold mb-4\">교육과정</h3>\r\n");
      out.write("	<div class=\"cms-sub-content\" data-cms-sub-content=\"OeiseRXwkjpx\">\r\n");
      out.write("		<div class=\"curriculum-top-box\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<p>\r\n");
      out.write("					좀 더 자세한 교육과정은 KNU 교육과정 사이트에 <br>\r\n");
      out.write("					상세하게 나와있습니다.\r\n");
      out.write("				</p>\r\n");
      out.write("				<a class=\"text-decoration-none\" href=\"https://curriculum.kangwon.ac.kr/\" target=\"_blank\" title=\"새창열림\"><span>KNU 교육과정 바로가기</span></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/fboard.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<SCRIPT language=\"javascript\">\r\n");
      out.write(" function check(){\r\n");
      out.write("  with(document.msgsearch){\r\n");
      out.write("   if(sval.value.length == 0){\r\n");
      out.write("    alert(\"검색어를 입력해 주세요!!\");\r\n");
      out.write("    sval.focus();\r\n");
      out.write("    return false;\r\n");
      out.write("   }	\r\n");
      out.write("   document.msgsearch.submit();\r\n");
      out.write("  }\r\n");
      out.write(" }\r\n");
      out.write(" /*\r\n");
      out.write(" function rimgchg(p1,p2) {\r\n");
      out.write("  if (p2==1) \r\n");
      out.write("   document.images[p1].src= \"image/open.gif\";\r\n");
      out.write("  else\r\n");
      out.write("   document.images[p1].src= \"image/arrow.gif\";\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(" function imgchg(p1,p2) {\r\n");
      out.write("  if (p2==1) \r\n");
      out.write("   document.images[p1].src= \"image/open.gif\";\r\n");
      out.write("  else\r\n");
      out.write("   document.images[p1].src= \"image/close.gif\";\r\n");
      out.write(" }\r\n");
      out.write(" */\r\n");
      out.write("</SCRIPT>\r\n");
      out.write('\r');
      out.write('\n');

	Connection con = null;

	String url = "jdbc:mysql://localhost:3306/fboard";
	String user = "root";
	String password = "1234";

	Class.forName("com.mysql.jdbc.Driver");
	con = DriverManager.getConnection(url, user, password);

      out.write("\r\n");
      out.write("  <div class=\"container pb-4\">\r\n");
      out.write("    <P>\r\n");
      out.write("    <P align=center><FONT color=#0000ff face=굴림 size=5><STRONG>공지사항</STRONG></FONT></P> \r\n");
      out.write("    <P>\r\n");
      out.write("    <CENTER>\r\n");
      out.write("      <TABLE class=\"table\">\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr class=\"b-hed\" align=\"center\">\r\n");
      out.write("            <th scope=\"col\">번호</th>\r\n");
      out.write("            <!-- 제목이 원래 300 지정되었던 녀석 -->\r\n");
      out.write("            <th scope=\"col\" width=\"300\">제목</th>\r\n");
      out.write("            <th scope=\"col\">등록자</th>\r\n");
      out.write("            <th scope=\"col\">날짜</th>\r\n");
      out.write("            <th scope=\"col\">조회</th>\r\n");
      out.write("            <td scope=\"col\">감춤</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("    ");
 
      Vector name=new Vector();
      Vector inputdate=new Vector();
      Vector email=new Vector();
      Vector subject=new Vector();
      Vector rcount=new Vector();
      
      Vector step=new Vector();
      Vector keyid=new Vector();
      int where=1;

      int totalgroup=0;
      int maxpages=2;
      int startpage=1;
      int endpage=startpage+maxpages-1;
      int wheregroup=1;

      if (request.getParameter("go") != null) {
      where = Integer.parseInt(request.getParameter("go"));
      wheregroup = (where-1)/maxpages + 1;
      startpage=(wheregroup-1) * maxpages+1;  
      endpage=startpage+maxpages-1; 
      } else if (request.getParameter("gogroup") != null) {
      wheregroup = Integer.parseInt(request.getParameter("gogroup"));
      startpage=(wheregroup-1) * maxpages+1;  
      where = startpage ; 
      endpage=startpage+maxpages-1; 
      }
      int nextgroup=wheregroup+1;
      int priorgroup= wheregroup-1;

      int nextpage=where+1;
      int priorpage = where-1;
      int startrow=0;
      int endrow=0;
      int maxrows=5;
      int totalrows=0;
      int totalpages=0;

      int id=0;

      String em=null;
      //  Connection con= null;
      Statement st =null;
      ResultSet rs =null;
    
      
    try {
      st = con.createStatement();
      String sql = "select * from freeboard order by" ;
      sql = sql + " masterid desc, replynum, step, id" ;
      rs = st.executeQuery(sql);

      if (!(rs.next()))  {
      out.println("게시판에 올린 글이 없습니다");
      } else {
      do {
        keyid.addElement(new Integer(rs.getInt("id")));
        name.addElement(rs.getString("name"));
        email.addElement(rs.getString("email"));
        String idate = rs.getString("inputdate");
        idate = idate.substring(0,8);
        inputdate.addElement(idate);
        subject.addElement(rs.getString("subject"));
        rcount.addElement(new Integer(rs.getInt("readcount")));
        step.addElement(new Integer(rs.getInt("step")));
      }while(rs.next());
      totalrows = name.size();
      totalpages = (totalrows-1)/maxrows +1;
      startrow = (where-1) * maxrows;
      endrow = startrow+maxrows-1  ;
      if (endrow >= totalrows)
        endrow=totalrows-1;
      
      totalgroup = (totalpages-1)/maxpages +1;
      if (endpage > totalpages) 
        endpage=totalpages;

      for(int j=startrow;j<=endrow;j++) {
        String temp=(String)email.elementAt(j);
        if ((temp == null) || (temp.equals("")) ) 
        em= (String)name.elementAt(j); 
        else
        em = "<A class='text-decoration-none' href=mailto:" + temp + ">" + name.elementAt(j) + "</A>";

        id= totalrows-j;
        if(j%2 == 0){
        out.println("<TR bgcolor='#FFFFFF' onMouseOver=\" bgColor= '#DFEDFF'\" onMouseOut=\"bgColor=''\">");	
        } else {
        out.println("<TR bgcolor='#F4F4F4' onMouseOver=\" bgColor= '#DFEDFF'\" onMouseOut=\"bgColor='#F4F4F4'\">");
        } 
        out.println("<TD  class=\"b-hed\" align=center>");
        out.println(id+"</TD>");
        out.println("<TD class=\"b-hed\">");
        int stepi= ((Integer)step.elementAt(j)).intValue();
        int imgcount = j-startrow; 
        if (stepi > 0 ) {
        for(int count=0; count < stepi; count++)
          out.print("&nbsp;&nbsp;");
        out.println("<IMG name=icon"+imgcount+ " src=../community/freeboard/image/arrow.gif>");
        out.print("<A class='text-decoration-none' href=../community/freeboard/freeboard_read.jsp?table=freeboard&id=");
        out.print(keyid.elementAt(j) + "&page=" + where );
        out.print(" onmouseover=\"rimgchg(" + imgcount + ",1)\"");
        out.print(" onmouseout=\"rimgchg(" + imgcount + ",2)\">");
        } else {
        out.println("<IMG name=icon"+imgcount+ " src=../community/freeboard/image/close.gif>");
        out.print("<A class='text-decoration-none' href=../community/freeboard/freeboard_read.jsp?table=freeboard&id=");
        out.print(keyid.elementAt(j) + "&page=" + where );
        out.print(" onmouseover=\"imgchg(" + imgcount + ",1)\"");
        out.print(" onmouseout=\"imgchg(" + imgcount + ",2)\">");
        }
        out.println(subject.elementAt(j) + "</a></TD>");
        out.println("<TD class=\"b-hed\" align=center>");
        out.println(em+ "</TD>");
        out.println("<TD class=\"b-hed\" align=center>");
        out.println(inputdate.elementAt(j)+ "</TD>");
        out.println("<TD class=\"b-hed\" align=center>");
        out.println(rcount.elementAt(j)+ "</TD>");

        
        
    // 추가    
        out.println("<td>");

        if (stepi > 0 ) {
            for(int count=0; count < stepi; count++)
    //         out.print("&nbsp;&nbsp;");
            out.println("<div class=\"container_div\"><IMG name=icon"+imgcount+ " src=../community/freeboard/image/arrow.gif>");
            out.print("<A class='text-decoration-none' href=../community/freeboard/freeboard_read.jsp?table=freeboard&id=");
            out.print(keyid.elementAt(j) + "&page=" + where );
            out.print(" onmouseover=\"rimgchg(" + imgcount + ",1)\"");
            out.print(" onmouseout=\"rimgchg(" + imgcount + ",2)\">");
          } else {
            out.println("<div class=\"container_div\"><IMG name=icon"+imgcount+ " src=../community/freeboard/image/close.gif>");
            out.print("<A class='text-decoration-none' href=../community/freeboard/freeboard_read.jsp?table=freeboard&id=");
            out.print(keyid.elementAt(j) + "&page=" + where );
            out.print(" onmouseover=\"imgchg(" + imgcount + ",1)\"");
            out.print(" onmouseout=\"imgchg(" + imgcount + ",2)\">");
          }
        out.println(subject.elementAt(j) + "</a>");
        out.println("<div class=\"container_div\" align=\"right\"><small>");
        out.println(em+ "&nbsp;&nbsp; | &nbsp;&nbsp;");
        out.println(inputdate.elementAt(j)+ "&nbsp;&nbsp; | &nbsp;&nbsp;조회수 : ");
        out.println(rcount.elementAt(j)+ "</small></div>");
        out.println("</div>");  
        out.println("</TD>");
    //추가 끝    
        
        out.println("</TR>");
      }
      rs.close();
      }
      out.println("</TABLE>");
      st.close();
      con.close();
    } catch (java.sql.SQLException e) {
      out.println(e);
    } 

    if (wheregroup > 1) {
      out.println("[<A href=../community/freeboard/freeboard_list.jsp?table=freeboard&gogroup=1>처음</A>]"); 
      out.println("[<A href=../community/freeboard/freeboard_list.jsp?table=freeboard&gogroup="+priorgroup +">이전</A>]");
    } else {
      out.println("[처음]") ;
      out.println("[이전]") ;
    }
    if (name.size() !=0) { 
      for(int jj=startpage; jj<=endpage; jj++) {
      if (jj==where) 
        out.println("["+jj+"]") ;
      else
        out.println("[<A href=../community/freeboard/freeboard_list.jsp?table=freeboard&go="+jj+">" + jj + "</A>]") ;
      } 
      }
      if (wheregroup < totalgroup) {
      out.println("[<A href=../community/freeboard/freeboard_list.jsp?table=freeboard&gogroup="+ nextgroup+ ">다음</A>]");
      out.println("[<A href=../community/freeboard/freeboard_list.jsp?table=freeboard&gogroup="+ totalgroup + ">마지막</A>]");
      } else {
      out.println("[다음]");
      out.println("[마지막]");
      }
      out.println ("전체 글수 :"+totalrows); 
    
      out.write("\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <FORM class=\"form-inline\" method=\"post\" name=\"msgsearch\" action=\"../community/freeboard/freeboard_search.jsp?table=freeboard\">\r\n");
      out.write("          <div class=\"container_div\">\r\n");
      out.write("            <div class=\"row form-group\">\r\n");
      out.write("              <SELECT class=\"col form-control offset-md-7\" name=\"stype\" >\r\n");
      out.write("                <OPTION value=1 >이름\r\n");
      out.write("                <OPTION value=2 >제목\r\n");
      out.write("                <OPTION value=3 >내용\r\n");
      out.write("                <OPTION value=4 >이름+제목\r\n");
      out.write("                <OPTION value=5 >이름+내용\r\n");
      out.write("                <OPTION value=6 >제목+내용\r\n");
      out.write("                <OPTION value=7 >이름+제목+내용\r\n");
      out.write("              </SELECT>\r\n");
      out.write("              &nbsp;\r\n");
      out.write("              <INPUT class=\"col form-control\" type=text  name=\"sval\" placeholder=\"내용입력하세요\"> \r\n");
      out.write("              &nbsp;\r\n");
      out.write("              <a class=\"col-auto p-0 me-3\" href=\"#\" onClick=\"check();\"><button type=\"button\" class=\"btn btn-success\">검색</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <div align=right><A href=\"../community/freeboard/freeboard_write.jsp?table=freeboard\"><img src=\"../community/freeboard/image/write.gif\" class=\"img-fluid\"></A></div>\r\n");
      out.write("          </div>\r\n");
      out.write("       </FORM>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("  </CENTER>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("	<div class=\"row justify-content-between rounded p-3\" style=\"background: #D6D8D9\">\r\n");
      out.write("		<div class=\"col-auto ps-0\">\r\n");
      out.write("			<div>\r\n");
      out.write("				");

					String[] myHref = {"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=9&key=79", "https://www.kangwon.ac.kr/www/contents.do?key=334", "https://www.kangwon.ac.kr/www/contents.do?key=343", 
									   "#", "https://www.kangwon.ac.kr/www/selectEmpList.do?key=55", "https://www.academyinfo.go.kr/popup/pubinfo1690/list.do?schlId=0000003"};
					String[] myText = {"청렴행정", "개인정보처리방침","이메일주소수집거부",
									   "웹마스터", "전화번호검색", "대학정보공시"};

					if(myHref.length == myText.length)
					{
						for(int i = 0; i < myHref.length; i++)
						{
				
      out.write("\r\n");
      out.write("							<a class=\"text-decoration-none visit-orange\" target=\"_blank\" href=");
      out.print(myHref[i]);
      out.write('>');
      out.print(myText[i]);
      out.write("</a>\r\n");
      out.write("				");

							if(i < myHref.length - 1) out.println("|");
						}
					}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"btn btn-secondary dropdown-toggle px-3 py-2 fw-normal fs-4\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-offset=\"0,-800\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("					교내사이트 바로가기\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("					<div>\r\n");
      out.write("						");

							String[] otherHref = {"http://knugift.co.kr/", "https://cube.kangwon.ac.kr/portal/index", "https://cms.kangwon.ac.kr/padm/life/general-notice.do?mode=view&articleNo=243895&article.offset=760&articleLimit=10", 
											      "http://knufc.kr/bbs/login.php", "https://tpsc.kangwon.ac.kr/", "https://curriculum.kangwon.ac.kr/", "https://linc.kangwon.ac.kr/", "https://fund.kangwon.ac.kr/", 
											      "https://www.knuh.or.kr/main/main.asp", "http://knup.kangwon.ac.kr/", "https://ile.kangwon.ac.kr:44303/", "https://kculture.kangwon.ac.kr/", "http://knubiornd.com/", "https://kiit.kr/lang_kr.php?pid=index",
											      "https://kwbi.kangwon.ac.kr/", "http://old.kwclab.co.kr/", "http://clab.kwclab.co.kr/default.asp", "http://gongja.kangwon.ac.kr/", "https://icee.kangwon.ac.kr/", "https://gifted.kangwon.ac.kr/",
											      "https://faculty.kangwon.ac.kr/", "https://kile.kangwon.ac.kr/", "http://keri.kangwon.ac.kr/", "https://teacher.kangwon.ac.kr/teacher/index.do", "https://itl.kangwon.ac.kr/",
											      "https://oiaknu.kangwon.ac.kr/oiaknu/index.do", "http://www.iird.or.kr/", "https://www.kangwon.ac.kr/kwrc/index.do", "https://www.kbsi.re.kr/", "http://alsri.kangwon.ac.kr/", "http://www.nongsa.or.kr/"};
							String[] otherText = {"KNU 기념품 쇼핑몰", "KNU-큐브 & 메이커스페이스", "강원권역 e-러닝 지원센터", "강원대학교 교수회", "강원대학교 교원양성지원센터",
											      "강원대학교 교육과정", "강원대학교LINC사업단", "강원대학교 발전기금재단", "강원대학교병원", "강원대학교신문방송사",
											      "강원대학교평생학습중심대학", "강원문화연구소", "강원웰빙특산물산업화지역혁신센터", "강원종합기술연구원", "강원창업보육센터",
											      "공동실헙실습관", "공동실헙실습관(삼척)", "공자학원", "공학교육혁신센터", "과학영재교육원",
											      "교원초빙", "교양교육원", "교육연구소", "교육연수원", "교육혁신원",
											      "국제교류처", "국제농촌개발협력사업단", "글쓰기센터", "기초과학연구소", "농업생명과학연구원", "농촌사회교육원"};

							if(otherHref.length == otherText.length)
							{
								for(int i = 0; i < otherHref.length; i++)
								{
						
      out.write("\r\n");
      out.write("									<li class=\"dropdown-item\"><span class=\"px-2\">•</span><a class=\"text-decoration-none\" target=\"_blank\" href=");
      out.print(otherHref[i]);
      out.write('>');
      out.print(otherText[i]);
      out.write("</a></li>\r\n");
      out.write("						");

								}
							}
						
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row mt-3 mb-5\">\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<img style=\"width:200px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-footer-logo.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto p-0 ms-5\">\r\n");
      out.write("			<div class=\"row row-cols-1\" style=\"font-size:13px;max-width:800px\">\r\n");
      out.write("				<div class=\"col-auto pb-3\">\r\n");
      out.write("					강원도 삼척시 중앙로 346 강원대학교 삼척캠퍼스 5공학관 5층 | 대표전화: \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6370\" title=\"전화걸기\">033-570-6370</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6340\" title=\"전화걸기\">6430</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6580\" title=\"전화걸기\">6580</a> | 팩스 : 033-570-6379, 6589\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto\">\r\n");
      out.write("					COPYRIGHT (C) 2017 BY KANGWON NATIONAL UNIVERSITY.ALL RIGHTS RESERVED.\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/jquery/jquery-3.6.0.slim.min.js\"></script>\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
