/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-06-06 09:01:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.professor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class professor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/professor/../link.txt", Long.valueOf(1654501137130L));
    _jspx_dependants.put("/professor/../footer.jsp", Long.valueOf(1650729964323L));
    _jspx_dependants.put("/professor/../menu.jsp", Long.valueOf(1654506087535L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/bootstrap-5.1.3-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/header.content0b7a.css?after\" />");
      out.write("\r\n");
      out.write("<title>교수 | AI소프트웨어학과</title>\r\n");
      out.write("<style>\r\n");
      out.write(".form-select {\r\n");
      out.write("	background:#fff url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' width='4' height='5' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e\") right .75rem center/8px 10px no-repeat;\r\n");
      out.write("}\r\n");
      out.write(".btn-mybtn{\r\n");
      out.write("	color: #007575;\r\n");
      out.write("	border-color: #98d6d6;\r\n");
      out.write("	background-color: rgba(0, 117, 117, 0.3);\r\n");
      out.write("}\r\n");
      out.write(".btn-mybtn:hover{\r\n");
      out.write("	color: #FFFFFF;\r\n");
      out.write("	border-color: #007575;\r\n");
      out.write("	background-color: #007575;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<nav class=\"row navbar navbar-expand navbar-light bg-light\">\r\n");
      out.write("		<div class=\"row justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto\">\r\n");
      out.write("				<div class=\"navbar-header\">\r\n");
      out.write("					<div class=\"bottom-header-box\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<a class=\"text-decoration-none\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" title=\"홈 바로가기\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-logo.png\" alt=\"KNU\">\r\n");
      out.write("									<br><span class=\"logo-txt\">AI소프트웨어학과</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"logo-bottom\">KANGWON NATIONAL UNIVERSITY</p>\r\n");
      out.write("							</a>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto ps-0 pe-0\">\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarNavLightDropdown\">\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학과소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/greetings.jsp\">인사말</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history04.jsp\">학과연혁</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/intro.jsp\">학과소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/lab.jsp\">실습실소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/circle.jsp\">동아리소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/council.jsp\">학생회소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/location.jsp\">오시는 길</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								교수소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/professor/professor.jsp\">교수</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/professor/emeritus-professor.jsp\">명예교수</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학사안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" target=\"_blank\" href=\"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37&key=1176&)\">학사공지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/curriculum.jsp\">교육과정</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/subject.jsp\">편성교과목</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/info.jsp\">학사정보</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/calendar.jsp\">학사일정</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								입학안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admission/admission-guide.jsp\">모집요강</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								커뮤니티\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=freeboard\">공지사항</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=gallery\">갤러리</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=dataroom\">서식자료실</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto pe-0\">\r\n");
      out.write("				<div class=\"row g-2 align-items-center\">\r\n");
      out.write("					<form class=\"col-auto m-0\">\r\n");
      out.write("						<div class=\"row g-2 justify-content-end\" style=\"max-width: 260px\">\r\n");
      out.write("							<div class=\"col-8\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"search\" placeholder=\"Search\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-success\">Search</button>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"col-auto m-0\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<div class=\"container px-0 mb-5\">\r\n");
      out.write("	<h3 class=\"fw-bold mb-4\">교수</h3>\r\n");
      out.write("	<form class=\"form-inline bg-light\" method=\"post\" name=\"msgsearch\" action=\"#\">\r\n");
      out.write("		<div class=\"container_div py-2 me-3\">\r\n");
      out.write("			<div class=\"row form-group justify-content-end\">\r\n");
      out.write("				<select class=\"col form-select offset-md-7\" name=\"stype\" style=\"max-width:80px;\">\r\n");
      out.write("					<option selected>이름</option>\r\n");
      out.write("					<option value=\"1\">제목</option>\r\n");
      out.write("					<option value=\"2\">내용</option>\r\n");
      out.write("					<option value=\"3\">이름+제목</option>\r\n");
      out.write("					<option value=\"4\">이름+내용</option>\r\n");
      out.write("					<option value=\"5\">제목+내용</option>\r\n");
      out.write("					<option value=\"6\">이름+제목+내용</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				 &nbsp; \r\n");
      out.write("				 <input class=\"col form-control\" type=text name=\"sval\" placeholder=\"검색어를 입력해 주세요\" style=\"max-width:250px;\"> \r\n");
      out.write("				 &nbsp; \r\n");
      out.write("				 <a class=\"col-auto p-0 me-3\" href=\"#\" onclick=\"check();\">\r\n");
      out.write("				 	<button type=\"button\" class=\"btn btn-outline-success\">검색</button>\r\n");
      out.write("				 </a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"이태민\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_664_1646725165000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">이태민</span> 조교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>컴퓨터그래픽스,감성컴퓨팅,증강/가상현실,인공지능</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 416호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6378\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6378 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:kevinlee@kangwon.ac.kr\" title=\"메일보내기\">kevinlee@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"황득영\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_272_1632460249000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">황득영</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>병렬컴파일러/프로그래밍언어론</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 514호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6376\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6376 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:dyhwang@kangwon.ac.kr\" title=\"메일보내기\">dyhwang@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"../professor0284.jsp\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"유희경\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_267_1632459664000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">유희경</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>컴퓨터보안/빅데이터/전산통계학</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 417호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6371\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6371 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:hkyoo@kangwon.ac.kr\" title=\"메일보내기\">hkyoo@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"이두호\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_273_1632460345000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">이두호</span> 부교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>대기행렬 시스템/최적화/게임이론</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 506호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6583\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6583 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:enjdhlee@kangwon.ac.kr\" title=\"메일보내기\">enjdhlee@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"박은희\" src=\"https://aisw.kangwon.ac.kr/_attach/gyosupic/11154.jpg\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">박은희</span> 조교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>응용수학/수치해석, 데이터과학</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 513호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6372\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6372 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:eh.park@kangwon.ac.kr\" title=\"메일보내기\">eh.park@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"권세진\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_268_1632460166000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">권세진</span> 부교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>임베디드 시스템 / 소프트웨어, 비휘발성 메모리</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 415호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6377\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6377 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:sjkwon@kangwon.ac.kr\" title=\"메일보내기\">sjkwon@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"윤종철\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_269_1632460183000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">윤종철</span> 부교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>영상처리, 가상/증강현실</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 609호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6869\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6869 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:media19@kangwon.ac.kr\" title=\"메일보내기\">media19@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"장영관\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_265_1632459459000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">장영관</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>물류정보시스템/MIS/ERP/SCM/인간공학</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 507호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6585\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6585 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:ykjang@kangwon.ac.kr\" title=\"메일보내기\">ykjang@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"문성동\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_266_1632459636000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">문성동</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>생산기계/공장자동화</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 508호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6586\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6586 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:sudom@kangwon.ac.kr\" title=\"메일보내기\">sudom@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"윤인섭\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_270_1632460204000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">윤인섭</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>자성체/방송조명/뉴미디어</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 515호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6374\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6374 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:isyoon@kangwon.ac.kr\" title=\"메일보내기\">isyoon@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6 mb-4\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"홍종성\" src=\"https://aisw.kangwon.ac.kr/_attach/gyosupic/10124.jpg\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">홍종성</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>음향공학/영상공학/문화기술연구</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 510호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6373\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6373 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:jshong@kangwon.ac.kr\" title=\"메일보내기\">jshong@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-6\">\r\n");
      out.write("			<div class=\"row rows-cols-1\">\r\n");
      out.write("				<div class=\"col-12 text-center mb-3\">\r\n");
      out.write("					<img width=\"189px\" height=\"248px\" alt=\"오형술\" src=\"https://aisw.kangwon.ac.kr/app/common/attach/image/thumb_264_1632459425000.do\" onerror=\"this.src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/board/img-faculty-default.gif'\"/>\r\n");
      out.write("					<div><span class=\"text-primary\">오형술</span> 교수</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-12 text-start\">\r\n");
      out.write("					<ul style=\"list-style:none;\">\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구분야 </span><span>PSS설계/SCM/네트워크 신뢰도</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연구실 </span><span>5공학관 509호</span>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>연락처 </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"tel:033-570-6584\" title=\"전화걸기\">\r\n");
      out.write("						033-570-6584 </a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("						<span>이메일 : </span>\r\n");
      out.write("						<a class=\"text-decoration-none\" href=\"mailto:hsoh@kangwon.ac.kr\" title=\"메일보내기\">hsoh@kangwon.ac.kr</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"mt-3\">\r\n");
      out.write("						<a class=\"text-decoration-none btn btn-mybtn\" href=\"#\" title=\"더보기\">더보기</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("	<div class=\"row justify-content-between rounded p-3\" style=\"background: #D6D8D9\">\r\n");
      out.write("		<div class=\"col-auto ps-0\">\r\n");
      out.write("			<div>\r\n");
      out.write("				");

					String[] myHref = {"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=9&key=79", "https://www.kangwon.ac.kr/www/contents.do?key=334", "https://www.kangwon.ac.kr/www/contents.do?key=343", 
									   "#", "https://www.kangwon.ac.kr/www/selectEmpList.do?key=55", "https://www.academyinfo.go.kr/popup/pubinfo1690/list.do?schlId=0000003"};
					String[] myText = {"청렴행정", "개인정보처리방침","이메일주소수집거부",
									   "웹마스터", "전화번호검색", "대학정보공시"};

					if(myHref.length == myText.length)
					{
						for(int i = 0; i < myHref.length; i++)
						{
				
      out.write("\r\n");
      out.write("							<a class=\"text-decoration-none visit-orange\" target=\"_blank\" href=");
      out.print(myHref[i]);
      out.write('>');
      out.print(myText[i]);
      out.write("</a>\r\n");
      out.write("				");

							if(i < myHref.length - 1) out.println("|");
						}
					}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"btn btn-secondary dropdown-toggle px-3 py-2 fw-normal fs-4\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-offset=\"0,-800\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("					교내사이트 바로가기\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("					<div>\r\n");
      out.write("						");

							String[] otherHref = {"http://knugift.co.kr/", "https://cube.kangwon.ac.kr/portal/index", "https://cms.kangwon.ac.kr/padm/life/general-notice.do?mode=view&articleNo=243895&article.offset=760&articleLimit=10", 
											      "http://knufc.kr/bbs/login.php", "https://tpsc.kangwon.ac.kr/", "https://curriculum.kangwon.ac.kr/", "https://linc.kangwon.ac.kr/", "https://fund.kangwon.ac.kr/", 
											      "https://www.knuh.or.kr/main/main.asp", "http://knup.kangwon.ac.kr/", "https://ile.kangwon.ac.kr:44303/", "https://kculture.kangwon.ac.kr/", "http://knubiornd.com/", "https://kiit.kr/lang_kr.php?pid=index",
											      "https://kwbi.kangwon.ac.kr/", "http://old.kwclab.co.kr/", "http://clab.kwclab.co.kr/default.asp", "http://gongja.kangwon.ac.kr/", "https://icee.kangwon.ac.kr/", "https://gifted.kangwon.ac.kr/",
											      "https://faculty.kangwon.ac.kr/", "https://kile.kangwon.ac.kr/", "http://keri.kangwon.ac.kr/", "https://teacher.kangwon.ac.kr/teacher/index.do", "https://itl.kangwon.ac.kr/",
											      "https://oiaknu.kangwon.ac.kr/oiaknu/index.do", "http://www.iird.or.kr/", "https://www.kangwon.ac.kr/kwrc/index.do", "https://www.kbsi.re.kr/", "http://alsri.kangwon.ac.kr/", "http://www.nongsa.or.kr/"};
							String[] otherText = {"KNU 기념품 쇼핑몰", "KNU-큐브 & 메이커스페이스", "강원권역 e-러닝 지원센터", "강원대학교 교수회", "강원대학교 교원양성지원센터",
											      "강원대학교 교육과정", "강원대학교LINC사업단", "강원대학교 발전기금재단", "강원대학교병원", "강원대학교신문방송사",
											      "강원대학교평생학습중심대학", "강원문화연구소", "강원웰빙특산물산업화지역혁신센터", "강원종합기술연구원", "강원창업보육센터",
											      "공동실헙실습관", "공동실헙실습관(삼척)", "공자학원", "공학교육혁신센터", "과학영재교육원",
											      "교원초빙", "교양교육원", "교육연구소", "교육연수원", "교육혁신원",
											      "국제교류처", "국제농촌개발협력사업단", "글쓰기센터", "기초과학연구소", "농업생명과학연구원", "농촌사회교육원"};

							if(otherHref.length == otherText.length)
							{
								for(int i = 0; i < otherHref.length; i++)
								{
						
      out.write("\r\n");
      out.write("									<li class=\"dropdown-item\"><span class=\"px-2\">•</span><a class=\"text-decoration-none\" target=\"_blank\" href=");
      out.print(otherHref[i]);
      out.write('>');
      out.print(otherText[i]);
      out.write("</a></li>\r\n");
      out.write("						");

								}
							}
						
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row mt-3 mb-5\">\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<img style=\"width:200px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-footer-logo.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto p-0 ms-5\">\r\n");
      out.write("			<div class=\"row row-cols-1\" style=\"font-size:13px;max-width:800px\">\r\n");
      out.write("				<div class=\"col-auto pb-3\">\r\n");
      out.write("					강원도 삼척시 중앙로 346 강원대학교 삼척캠퍼스 5공학관 5층 | 대표전화: \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6370\" title=\"전화걸기\">033-570-6370</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6340\" title=\"전화걸기\">6430</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6580\" title=\"전화걸기\">6580</a> | 팩스 : 033-570-6379, 6589\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto\">\r\n");
      out.write("					COPYRIGHT (C) 2017 BY KANGWON NATIONAL UNIVERSITY.ALL RIGHTS RESERVED.\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/jquery/jquery-3.6.0.slim.min.js\"></script>\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
