/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-06-06 12:46:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/./community/freeboard/dbconn.jsp", Long.valueOf(1652100541898L));
    _jspx_dependants.put("/./community/freeboard/board.jsp", Long.valueOf(1654519582398L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1650729964323L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1654506087535L));
    _jspx_dependants.put("/link.txt", Long.valueOf(1654501137130L));
    _jspx_dependants.put("/mainimage_first.jsp", Long.valueOf(1654427396585L));
    _jspx_dependants.put("/mainimage_second.jsp", Long.valueOf(1654512232081L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/bootstrap-5.1.3-dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/header.content0b7a.css?after\" />");
      out.write(' ');
      out.write("\r\n");
      out.write("    <title>AI소프트웨어학과</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<nav class=\"row navbar navbar-expand navbar-light bg-light\">\r\n");
      out.write("		<div class=\"row justify-content-between align-items-center\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto\">\r\n");
      out.write("				<div class=\"navbar-header\">\r\n");
      out.write("					<div class=\"bottom-header-box\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<a class=\"text-decoration-none\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" title=\"홈 바로가기\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-logo.png\" alt=\"KNU\">\r\n");
      out.write("									<br><span class=\"logo-txt\">AI소프트웨어학과</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"logo-bottom\">KANGWON NATIONAL UNIVERSITY</p>\r\n");
      out.write("							</a>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto ps-0 pe-0\">\r\n");
      out.write("				<div class=\"collapse navbar-collapse\" id=\"navbarNavLightDropdown\">\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학과소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/greetings.jsp\">인사말</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/history04.jsp\">학과연혁</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/intro.jsp\">학과소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/lab.jsp\">실습실소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/circle.jsp\">동아리소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/council.jsp\">학생회소개</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/intro/location.jsp\">오시는 길</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								교수소개\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/professor/professor.jsp\">교수</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/professor/emeritus-professor.jsp\">명예교수</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								학사안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" target=\"_blank\" href=\"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=37&key=1176&)\">학사공지</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/curriculum.jsp\">교육과정</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/subject.jsp\">편성교과목</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/info.jsp\">학사정보</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/calendar.jsp\">학사일정</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								입학안내\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admission/admission-guide.jsp\">모집요강</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<ul class=\"navbar-nav dropdown-content\">\r\n");
      out.write("						<li class=\"nav-item dropdown\">\r\n");
      out.write("							<a class=\"nav-link dropdown-toggle text-dark\" href=\"#\" id=\"navbarLightDropdownMenuLink\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("								커뮤니티\r\n");
      out.write("							</a>\r\n");
      out.write("							<ul class=\"dropdown-menu dropdown-menu-light\" aria-labelledby=\"navbarLightDropdownMenuLink\">\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=freeboard\">공지사항</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=gallery\">갤러리</a></li>\r\n");
      out.write("								<li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=dataroom\">서식자료실</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-auto pe-0\">\r\n");
      out.write("				<div class=\"row g-2 align-items-center\">\r\n");
      out.write("					<form class=\"col-auto m-0\">\r\n");
      out.write("						<div class=\"row g-2 justify-content-end\" style=\"max-width: 260px\">\r\n");
      out.write("							<div class=\"col-8\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" name=\"search\" placeholder=\"Search\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-auto\">\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-success\">Search</button>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<div class=\"col-auto m-0\">\r\n");
      out.write("							<button type=\"submit\" class=\"btn btn-primary\">Login</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</div>");
      out.write(' ');
      out.write("\r\n");
      out.write("        ");
      out.write("\n");
      out.write("<link defer rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/_common/css/cms.css\" />\n");
      out.write("<link defer rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/_share/css/swiper.min.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/_share/css/main-visual-temp08.widget03b3.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"/JspProject/project/_res/_common/js/jquery/jquery-2.2.4.min.js\"></script>\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/_common/js/cms.js\"></script>\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/knu/_share/js/swiper.min.js\"></script>\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/knu/_share/js/main-visual-temp08.widget03b3.js\" ></script>\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/knu/_share/js/board0472.js\" ></script>\n");
      out.write("<div class=\"main-visual-wrap cms-sub-content\" data-cms-sub-content=\"uCzOipLgRiIB\" style=\"width:100%\">\n");
      out.write("    <div>\n");
      out.write("        <div class=\"main-visual-box\">\n");
      out.write("            <div class=\"swiper-container main-visual-swiper\">\n");
      out.write("                <div class=\"swiper-wrapper\"> \n");
      out.write("                    <div class=\"swiper-slide\">\n");
      out.write("                        <div class=\"vi-img-box\" style=\"height:900px;min-height:auto;\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/aisw/img/main/1.jpg\" alt=\"AI소프트웨어학과\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"vi-txt-box\">\n");
      out.write("                            <p class=\"txt01\">미래를 예측하는 학문</p>\n");
      out.write("                            <p class=\"txt02\">강원대학교 AI소프트웨어학과</p>\n");
      out.write("                            <p class=\"txt03\">Department of Artificial Intelligence & Software</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"swiper-slide\">\n");
      out.write("                        <div class=\"vi-img-box\" style=\"height:900px;min-height:auto;\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/aisw/img/main/2.jpg\" alt=\"AI소프트웨어학과\">\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"vi-txt-box\">\n");
      out.write("                            <p class=\"txt01\">미래를 예측하는 학문</p>\n");
      out.write("                            <p class=\"txt02\">강원대학교 AI소프트웨어학과</p>\n");
      out.write("                            <p class=\"txt03\">Department of Artificial Intelligence & Software</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>     \n");
      out.write("                </div>\n");
      out.write("                <div class=\"control-wrap\">\n");
      out.write("                    <div class=\"swiper-visual-prev\">이전</div>\n");
      out.write("                    <div class=\"swiper-visual-next\">다음</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"swiper-visual-pagination\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<link defer rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/_common/css/cms.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/_share/css/announcement-mini-board-template-08-representative.widget1270.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/main3d9d.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/main-content01.content7204.css\" />\r\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/_common/js/cms.js\"></script>\r\n");
      out.write("<script defer type=\"text/javascript\" src=\"/JspProject/project/_res/knu/aisw/js/main-content01.content7204.js\" ></script>\r\n");
      out.write('\r');
      out.write('\n');

	Connection con = null;

	String url = "jdbc:mysql://localhost:3306/fboard";
	String user = "root";
	String password = "1234";

	Class.forName("com.mysql.jdbc.Driver");
	con = DriverManager.getConnection(url, user, password);

      out.write('\r');
      out.write('\n');

	PreparedStatement pstmt = null;
	ResultSet rs = null;
	
	String sql = "select id, inputdate, subject, content from ";
	String table = "";
	String order = " order by inputdate desc";
	String id = "";
	String inputdate = "";
	String subject = "";
	String content = "";
	
	int limit = 0;
	String href = "";

      out.write("\r\n");
      out.write("<div class=\"main-content-wrap01 cms-edit\" id=\"cms-content\">\r\n");
      out.write("	<div class=\"main-content-box main-content-box01 pt-5 pb-1\" style=\"display:block;height:auto;min-height:auto;\">\r\n");
      out.write("		<div class=\"main-mini-wrap row\">\r\n");
      out.write("			<div class=\"main-mini-box main-mini-box01 col-6 pb-0 pe-4\">\r\n");
      out.write("				<div class=\"mini-tab-box\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"active\"><a class=\"mini-board-tab \" href=\"#a\" title=\"공지사항\">공지사항</a>\r\n");
      out.write("						<div class=\"mini-board-content\">\r\n");
      out.write("							<div class=\"main-notice-box temp08\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									");

										try {
											table = "freeboard";
											
											String selectSQL = sql + table + order;
											pstmt = con.prepareStatement(selectSQL);
											rs = pstmt.executeQuery();
											
											rs.last();
											limit = rs.getRow();
											if(limit == 0){
												out.println("게시판에 올린 글이 없습니다");
											}
											else{
												limit = limit > 3 ? 3 : limit;
												rs.first();
												for(int i = 0 ; i < limit; i ++){
													id = rs.getString("id");
													inputdate = rs.getString("inputdate");
													inputdate = inputdate.substring(0,8);
													subject = rs.getString("subject");
													content = rs.getString("content");
													content = content.split("\n")[0];
													
													href = request.getContextPath() + "/community/freeboard/freeboard_read.jsp?table="+ table + "&id=" + id + "&page=1";
									
      out.write("\r\n");
      out.write("													<li>\r\n");
      out.write("														<p class=\"mini-date\">\r\n");
      out.write("															<span>");
      out.print(inputdate.substring(6, 8) );
      out.write("</span>");
      out.print((inputdate.substring(0, 5)).replace("-", ".") );
      out.write("\r\n");
      out.write("														</p>\r\n");
      out.write("														<div class=\"mini-txt-box\">\r\n");
      out.write("															<p class=\"mini-title\">\r\n");
      out.write("																<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(subject );
      out.write("</a>\r\n");
      out.write("															</p>\r\n");
      out.write("															<p class=\"mini-txt\">\r\n");
      out.write("																<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(content );
      out.write("</a>\r\n");
      out.write("															</p>\r\n");
      out.write("														</div>\r\n");
      out.write("													</li>\r\n");
      out.write("									");
				rs.next();
												}
											}
										}
										catch(SQLException ex){
											out.println(table + "테이블 호출이 실패했습니다.<br>");
											out.println("SQLException: " + ex.getMessage());
										}
									
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a class=\"btn-more\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=freeboard\" title=\"공지사항 바로가기 \">더보기</a></li>\r\n");
      out.write("						<li><a class=\"mini-board-tab\" href=\"#a\" title=\"갤러리\">갤러리</a>\r\n");
      out.write("						<div class=\"mini-board-content\">\r\n");
      out.write("							<div class=\"main-notice-box temp08\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									");

										try {
											table = "gallery";
											
											String selectSQL = sql + table + order;
											pstmt = con.prepareStatement(selectSQL);
											rs = pstmt.executeQuery();
											
											rs.last();
											limit = rs.getRow();
											if(limit == 0){
												out.println("게시판에 올린 글이 없습니다");
											}
											else{
												limit = limit > 3 ? 3 : limit;
												rs.first();
												for(int i = 0 ; i < limit; i ++){
													id = rs.getString("id");
													inputdate = rs.getString("inputdate");
													inputdate = inputdate.substring(0,8);
													subject = rs.getString("subject");
													content = rs.getString("content");
													content = content.split("\n")[0];
													
													href = request.getContextPath() + "/community/freeboard/freeboard_read.jsp?table="+ table + "&id=" + id + "&page=1";
									
      out.write("\r\n");
      out.write("													<li>\r\n");
      out.write("														<p class=\"mini-date\">\r\n");
      out.write("															<span>");
      out.print(inputdate.substring(6, 8) );
      out.write("</span>");
      out.print((inputdate.substring(0, 5)).replace("-", ".") );
      out.write("\r\n");
      out.write("														</p>\r\n");
      out.write("														<div class=\"mini-txt-box\">\r\n");
      out.write("															<p class=\"mini-title\">\r\n");
      out.write("																<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(subject );
      out.write("</a>\r\n");
      out.write("															</p>\r\n");
      out.write("															<p class=\"mini-txt\">\r\n");
      out.write("																<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(content );
      out.write("</a>\r\n");
      out.write("															</p>\r\n");
      out.write("														</div>\r\n");
      out.write("													</li>\r\n");
      out.write("									");
				rs.next();
												}
											}
										}
										catch(SQLException ex){
											out.println(table + "테이블 호출이 실패했습니다.<br>");
											out.println("SQLException: " + ex.getMessage());
										}
									
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<a class=\"btn-more\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=gallery\" title=\"갤러리 바로가기\">더보기</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"main-mini-box main-mini-box02 col-6 pb-0 ps-4\">\r\n");
      out.write("				<h3 class=\"main-title\">서식자료실</h3>\r\n");
      out.write("				<div class=\"main-notice-box temp08\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						");

							try {
								table = "dataroom";
								
								String selectSQL = sql + table + order;
								pstmt = con.prepareStatement(selectSQL);
								rs = pstmt.executeQuery();
								
								rs.last();
								limit = rs.getRow();
								if(limit == 0){
									out.println("게시판에 올린 글이 없습니다");
								}
								else{
									limit = limit > 3 ? 3 : limit;
									rs.first();
									for(int i = 0 ; i < limit; i ++){
										id = rs.getString("id");
										inputdate = rs.getString("inputdate");
										inputdate = inputdate.substring(0,8);
										subject = rs.getString("subject");
										content = rs.getString("content");
										content = content.split("\n")[0];
										
										href = request.getContextPath() + "/community/freeboard/freeboard_read.jsp?table="+ table + "&id=" + id + "&page=1";
						
      out.write("\r\n");
      out.write("										<li>\r\n");
      out.write("											<p class=\"mini-date\">\r\n");
      out.write("												<span>");
      out.print(inputdate.substring(6, 8) );
      out.write("</span>");
      out.print((inputdate.substring(0, 5)).replace("-", ".") );
      out.write("\r\n");
      out.write("											</p>\r\n");
      out.write("											<div class=\"mini-txt-box\">\r\n");
      out.write("												<p class=\"mini-title\">\r\n");
      out.write("													<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(subject );
      out.write("</a>\r\n");
      out.write("												</p>\r\n");
      out.write("												<p class=\"mini-txt\">\r\n");
      out.write("													<a href=");
      out.print(href );
      out.write(" title=\"자세히보기\">");
      out.print(content );
      out.write("</a>\r\n");
      out.write("												</p>\r\n");
      out.write("											</div>\r\n");
      out.write("										</li>\r\n");
      out.write("						");
				rs.next();
									}
								}
							}
							catch(SQLException ex){
								out.println(table + "테이블 호출이 실패했습니다.<br>");
								out.println("SQLException: " + ex.getMessage());
							}
							finally {
								if(rs != null)
									rs.close();
								if(pstmt != null)
									pstmt.close();
								if(con != null)
									con.close();
							}
						
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<a class=\"btn-more\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/freeboard/freeboard_list.jsp?table=dataroom\" title=\"서식자료실 바로가기\">더보기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("        ");
      out.write("\n");
      out.write("<link defer rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/_common/css/cms.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/main3d9d.css\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/JspProject/project/_res/knu/aisw/css/main-content02.content3d9d.css\" />\n");
      out.write("<div class=\"main-content-wrap02 cms-sub-content\" data-cms-sub-content=\"NyYNUsecryIS\" style=\"width:100%\">\n");
      out.write("	<div class=\"main-content-box main-content-box02 container pt-2\" style=\"display:block;height:auto;min-height:auto;\">\n");
      out.write("        <div class=\"main-mini-wrap row justify-content-between\">\n");
      out.write("            <div class=\"main-mini-box main-mini-box01 col-6 pe-4\">\n");
      out.write("                <h3 class=\"main-title\">전공소개</h3>\n");
      out.write("                <div class=\"main-video-box\">\n");
      out.write("                    <span class=\"fr-video fr-fvc fr-dvi fr-draggable\" >\n");
      out.write("                        <iframe width=\"100%\" height=\"125%\" src=\"https://www.youtube.com/embed/-io9f_63anc\" title=\"YouTube video player\" frameborder=\"0\" allowfullscreen=\"\" class=\"fr-draggable\">\n");
      out.write("                        </iframe>\n");
      out.write("                    </span>\n");
      out.write("                </div>\n");
      out.write("                <a class=\"btn-more\" href=\"/aisw/intro/intro.do\" rel=\"noopener noreferrer\" target=\"_blank\" title=\"전공소개 바로가기\" style=\"right:25px\">더보기</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"main-mini-box main-mini-box02 col-6 ps-4 pb-5\">\n");
      out.write("                <div class=\"main-quick-lnk-box\">\n");
      out.write("                    <div class=\"scrollert\">\n");
      out.write("                        <div class=\"scrollert-content\">\n");
      out.write("                            <ul>\n");
      out.write("                                <li><a href=\"https://www.youtube.com/channel/UCGkMqnKUlRD1OlulfCjPzwQ\" rel=\"noopener noreferrer\" target=\"_blank\" title=\"새창\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">AI소프트TV</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"https://www.youtube.com/channel/UCQzUE6Y0GimhZ3vlWyjcuRw\" rel=\"noopener noreferrer\" target=\"_blank\" title=\"새창\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">입시홍보관</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"https://kcloud.kangwon.ac.kr/login\" target=\"_blank\" title=\"K-Cloud 새창열림\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">K-Cloud</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"https://eruri.kangwon.ac.kr/login.php\" target=\"_blank\" title=\"e-루리 새창열림\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">e-루리</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"https://jobsc.kangwon.ac.kr/kwjob1/\" target=\"_blank\" title=\"취업센터 새창열림\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">취업센터</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"https://www.kangwon.ac.kr/www/contents.do?key=228&\" rel=\"noopener noreferrer\" target=\"_blank\" title=\"도서관 새창열림\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">장학안내</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bachelor/calendar.jsp\" rel=\"noopener noreferrer\" title=\"학사일정 바로가기\" style=\"text-decoration-line:none\">\n");
      out.write("                                        <div><p class=\"txt01\">학사일정</p></div>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<footer class=\"container\">\r\n");
      out.write("	<div class=\"row justify-content-between rounded p-3\" style=\"background: #D6D8D9\">\r\n");
      out.write("		<div class=\"col-auto ps-0\">\r\n");
      out.write("			<div>\r\n");
      out.write("				");

					String[] myHref = {"https://www.kangwon.ac.kr/www/selectBbsNttList.do?bbsNo=9&key=79", "https://www.kangwon.ac.kr/www/contents.do?key=334", "https://www.kangwon.ac.kr/www/contents.do?key=343", 
									   "#", "https://www.kangwon.ac.kr/www/selectEmpList.do?key=55", "https://www.academyinfo.go.kr/popup/pubinfo1690/list.do?schlId=0000003"};
					String[] myText = {"청렴행정", "개인정보처리방침","이메일주소수집거부",
									   "웹마스터", "전화번호검색", "대학정보공시"};

					if(myHref.length == myText.length)
					{
						for(int i = 0; i < myHref.length; i++)
						{
				
      out.write("\r\n");
      out.write("							<a class=\"text-decoration-none visit-orange\" target=\"_blank\" href=");
      out.print(myHref[i]);
      out.write('>');
      out.print(myText[i]);
      out.write("</a>\r\n");
      out.write("				");

							if(i < myHref.length - 1) out.println("|");
						}
					}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"btn btn-secondary dropdown-toggle px-3 py-2 fw-normal fs-4\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-offset=\"0,-800\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("					교내사이트 바로가기\r\n");
      out.write("				</button>\r\n");
      out.write("				<ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("					<div>\r\n");
      out.write("						");

							String[] otherHref = {"http://knugift.co.kr/", "https://cube.kangwon.ac.kr/portal/index", "https://cms.kangwon.ac.kr/padm/life/general-notice.do?mode=view&articleNo=243895&article.offset=760&articleLimit=10", 
											      "http://knufc.kr/bbs/login.php", "https://tpsc.kangwon.ac.kr/", "https://curriculum.kangwon.ac.kr/", "https://linc.kangwon.ac.kr/", "https://fund.kangwon.ac.kr/", 
											      "https://www.knuh.or.kr/main/main.asp", "http://knup.kangwon.ac.kr/", "https://ile.kangwon.ac.kr:44303/", "https://kculture.kangwon.ac.kr/", "http://knubiornd.com/", "https://kiit.kr/lang_kr.php?pid=index",
											      "https://kwbi.kangwon.ac.kr/", "http://old.kwclab.co.kr/", "http://clab.kwclab.co.kr/default.asp", "http://gongja.kangwon.ac.kr/", "https://icee.kangwon.ac.kr/", "https://gifted.kangwon.ac.kr/",
											      "https://faculty.kangwon.ac.kr/", "https://kile.kangwon.ac.kr/", "http://keri.kangwon.ac.kr/", "https://teacher.kangwon.ac.kr/teacher/index.do", "https://itl.kangwon.ac.kr/",
											      "https://oiaknu.kangwon.ac.kr/oiaknu/index.do", "http://www.iird.or.kr/", "https://www.kangwon.ac.kr/kwrc/index.do", "https://www.kbsi.re.kr/", "http://alsri.kangwon.ac.kr/", "http://www.nongsa.or.kr/"};
							String[] otherText = {"KNU 기념품 쇼핑몰", "KNU-큐브 & 메이커스페이스", "강원권역 e-러닝 지원센터", "강원대학교 교수회", "강원대학교 교원양성지원센터",
											      "강원대학교 교육과정", "강원대학교LINC사업단", "강원대학교 발전기금재단", "강원대학교병원", "강원대학교신문방송사",
											      "강원대학교평생학습중심대학", "강원문화연구소", "강원웰빙특산물산업화지역혁신센터", "강원종합기술연구원", "강원창업보육센터",
											      "공동실헙실습관", "공동실헙실습관(삼척)", "공자학원", "공학교육혁신센터", "과학영재교육원",
											      "교원초빙", "교양교육원", "교육연구소", "교육연수원", "교육혁신원",
											      "국제교류처", "국제농촌개발협력사업단", "글쓰기센터", "기초과학연구소", "농업생명과학연구원", "농촌사회교육원"};

							if(otherHref.length == otherText.length)
							{
								for(int i = 0; i < otherHref.length; i++)
								{
						
      out.write("\r\n");
      out.write("									<li class=\"dropdown-item\"><span class=\"px-2\">•</span><a class=\"text-decoration-none\" target=\"_blank\" href=");
      out.print(otherHref[i]);
      out.write('>');
      out.print(otherText[i]);
      out.write("</a></li>\r\n");
      out.write("						");

								}
							}
						
      out.write("\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row mt-3 mb-5\">\r\n");
      out.write("		<div class=\"col-auto\">\r\n");
      out.write("			<img style=\"width:200px\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/project/_res/knu/_share/img/common/img-footer-logo.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-auto p-0 ms-5\">\r\n");
      out.write("			<div class=\"row row-cols-1\" style=\"font-size:13px;max-width:800px\">\r\n");
      out.write("				<div class=\"col-auto pb-3\">\r\n");
      out.write("					강원도 삼척시 중앙로 346 강원대학교 삼척캠퍼스 5공학관 5층 | 대표전화: \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6370\" title=\"전화걸기\">033-570-6370</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6340\" title=\"전화걸기\">6430</a>, \r\n");
      out.write("					<a style=\"text-decoration-line:none\" href=\"tel:033-570-6580\" title=\"전화걸기\">6580</a> | 팩스 : 033-570-6379, 6589\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-auto\">\r\n");
      out.write("					COPYRIGHT (C) 2017 BY KANGWON NATIONAL UNIVERSITY.ALL RIGHTS RESERVED.\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/jquery/jquery-3.6.0.slim.min.js\"></script>\r\n");
      out.write("<script src=\"/JspProject/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js\"></script>");
      out.write(' ');
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
